### PR TITLE
Adding Certora Benchmarks

### PR DESCRIPTION
**Pull request by jar-ben**
Dear SMT-LIB benchmarks maintainers,

I would like to submit `462` benchmarks produced by the Certora Prover, i.e. a tool for formal verification of Ethereum Smart Contracts. The benchmarks encode verification conditions for real Smart Contracts (programs) written by our customers. 

The Certora Prover uses various strategies and SMT encodings of the underlying verification problem. In most cases, we use either `LIA`, `NIA` or `BV` encodings, where:
1. `LIA` is typically an overapproximation of the underlying verification problem.
2. `NIA` is typically a precise encoding.
3. `BV` is required when the input contains non-trivial bitwise operations that we do not model precisely with `NIA` (i.e., in these cases, `NIA` is an overapproximation). 

Note that our specification language allows unbounded integers (i.e. mathints); this the reason why we need `NIA` and `LIA` instead of using just `BV`.

We also use various encodings of "underlying hashing functions"; the two main encodings we use rely on i) `UF` and ii) on `UFDT`. Therefore, given a single input (a smart contract and a specification), we typically produce 6 different encodings: `QF_UFNIA`, `QF_UFLIA`, `QF_UFBV`, `QF_UFDTNIA`, `QF_UFDTLIA`, and `QF_UFDTBV`. The `462` benchmarks we submit originate from `77` unique smart contracts and specifications (`77*6 = 462`) and can be mapped based on the common name-prefix of the files. For instances:
```
./non-incremental/QF_UFBV/20230314-Jaroslav-Bendik-Certora/940_590f27b1c3c800d3243e_33_QF_UFBV.smt2
./non-incremental/QF_UFDTLIA/20230314-Jaroslav-Bendik-Certora/940_590f27b1c3c800d3243e_33_QF_UFDTLIA.smt2
./non-incremental/QF_UFLIA/20230314-Jaroslav-Bendik-Certora/940_590f27b1c3c800d3243e_33_QF_UFLIA.smt2
./non-incremental/QF_UFDTBV/20230314-Jaroslav-Bendik-Certora/940_590f27b1c3c800d3243e_33_QF_UFDTBV.smt2
./non-incremental/QF_UFDTNIA/20230314-Jaroslav-Bendik-Certora/940_590f27b1c3c800d3243e_33_QF_UFDTNIA.smt2
./non-incremental/QF_UFNIA/20230314-Jaroslav-Bendik-Certora/940_590f27b1c3c800d3243e_33_QF_UFNIA.smt2
```

I do not know the status (satisfiability) of the particular submitted benchmarks, though, I expect that around `80 %` are SAT and `20 %` are UNSAT. Around `50 %` should be solvable using a reasonable timelimit. 

I hope the community will find our benchmarks useful and interesting. 

Best regards, 
Jaroslav Bendik
(SMT Team Lead at Certora).

### CODE REVIEW

**Comment by hansjoergschurr** [comment]
Thank you very much for submitting the benchmarks.

I wonder if we could add parts of the description of how the benchmark set was generated to the `set-info :source` part of the benchmark.  The text would go below the `Publications:` line.

**Comment by hansjoergschurr** [comment]
I took the liberty to add the description of the benchmark set you provided here to the benchmark themselves with minor edits.  Thank you again the submission.  If everything goes well the benchmarks should be part of the next release.

**Comment by jar-ben** [comment]
@hansjoergschurr Thank you for adding the info to the .smt2 files! And let me apologise for taking so much time to reply; I was enjoying the Easter holiday.

**Comment by hansjoergschurr** [comment]
No problem, I just came around finish to your benchmarks earlier than I expected ^^.

**Pull request merged**
