### PR TITLE
OISC + GRS benchmarks

### PR DESCRIPTION
**Pull request by m-fleury**
Here are two different sets of benchmarks in a single merge requests (I hope that is okay).

1. OISC benchmarks based on the masters thesis by @SonjaGurtner (supervised by @LucasKl and @grossed)
    The tool we use does already some bit-blasting, so we quickly hit the 50MB limit. Here are some benchmarks that are a bit over the limit: those can be downloaded [here](cca.informatik.uni-freiburg.de/benchmarks/smt/2023/20230221-oisc-gurtner-too-large.tar.xz).
3. GRS benchmarks based on the upcoming bachelor thesis by @Robin060500 (supervised by @arminbiere and me @m-fleury).

### CODE REVIEW

**Comment by m-fleury** [comment]
The error from the basic-checks are not very useful to me:

```
Run jitterbit/get-changed-files@v1
  with:
    token: ***
    format: space-delimited
Base commit: dea6ad0096f57a46dd508cba087a4eb50e8611f2
Head commit: 1f0437c3acbbd3c4b6fa5e2b4b2c5a43f821f148
Error: Server Error: Sorry, this diff is taking too long to generate.: {"resource":"Comparison","field":"diff","code":"not_available"}
```

Does anyone know what I should do?

**Comment by mpreiner** [comment]
Can you try running `quick-check.sh` and `dolmen` locally as described in the [README](https://github.com/SMT-LIB/benchmark-submission/blob/main/README.md)?

**Comment by m-fleury** [comment]
They don't produce errors:
```
$ find . -name \*.smt2 -exec ./quick-check.sh {} \;  | grep error
# no output, no error
$ find . -name \*.smt2 -exec dolmen -s 20G -i smt2 --check-headers=true --header-lang-version=2.6 {} \;
# no output, no error
```

**Comment by hansjoergschurr** [comment]
It seems like some Github action we are using as a fairly low timeout limit or is very slow.

However, since some of the OSIC benchmarks were over the >50MB limit I added all OSIC benchmarks to the old-style pending repository: https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks-tmp/pending-2023/-/tree/main/TODO/non-incremental/QF_BV/20230221-oisc-gurtner

I suggest to remove the OSIC benchmarks from this pull request and to use it just for the GRS benchmarks.

**Comment by m-fleury** [comment]
Done. I rewrote the history to remove the benchmarks. Seems that someone needs to approve a run of the workflow.

**Comment by hansjoergschurr** [comment]
Thank you and your colleagues very much for the benchmark submission.  I removed the leading white space from the metadata lines and merged the branch.  We will run some further checks on our side, but if everything goes well you should see your benchmarks in the next benchmark release.

**Pull request merged**
