### PR TITLE
Added benchmarks from AWS NSym (Arm Symbolic Simulator)

### PR DESCRIPTION
**Pull request by nwetzler**
We have included some benchmarks produced by NSym, our symbolic simulator for Arm assembly code.  The problems fit into two categories.  The first are the raw benchmarks produced by the simulator, many of which are unknown by current solvers.  The second are the problems after some manual and automated rewriting which makes the problems much easier to solve.  We hope this will help motivate the community to identify opportunities to improve machine-code proofs via SMT.

Courtesy of Amazon Web Services - Automated Reasoning Group - Low Level Code Reasoning Team.

### CODE REVIEW

**Comment by hansjoergschurr** [comment]
This is great!  Thank you for your contribution.

It is also a good reminder for us that it is time to prepare a new benchmark submission repository for the coming release cycle.  Unfortunately, we bumped against some limitations with the current Github workflow last year.  We will have to overhaul those.

I will leave this pull request open for now, and let you know when the new repository is ready.

**Comment by hansjoergschurr** [comment]
The new repository is now ready: https://github.com/SMT-LIB/benchmark-submission
Feel free to open a pull request against it.

**Comment by nwetzler** [comment]
I've just opened a PR against the 2024 benchmark submission repo:
https://github.com/SMT-LIB/benchmark-submission/pull/3

**Comment by hansjoergschurr** [comment]
Thank you very much! I will close the pull request here.

**Pull request closed without merging**
