### PR TITLE
Submit Woorpje Track05 Benchmarks

### PR DESCRIPTION
**Pull request by JohnLyu2**
Benchmark Suite Description: https://github.com/JohnLyu2/woorpje_we

On my MAC, when I run dolmen on this track05, it usually throw errors. I checked the reason is that there are linear integer constraints like: _(assert (>=(* (str.len H) 8) 8))_. I think this is a valid assertion in QF_SLIA. Can you help me check does dolmen report error on your side? Thx.

### CODE REVIEW

**Comment by JohnLyu2** [comment]
I also submitted the rest of the benchmarks.

Automatark page: https://github.com/JohnLyu2/automatark_smt

**Comment by hansjoergschurr** [comment]
I noticed that you added a `Description:` line to the benchmarks.  Thank you!

Unfortunately, the idea is that such extra lines come after the last of the predefined lines  in the `set-info :source ` command.  So we will have to move your `Description:` line after the `Publications:` line.

I realize that the README is not very clear in this regard. We will improve it.

**Comment by hansjoergschurr** [comment]
I will merge this branch and perform the edit on our side.  I did this on your other submission.

Thank you again for your benchmark submission!

**Comment by JohnLyu2** [comment]
Thank you so much! Have a nice weekend : )
________________________________

**Pull request merged**
